# Logistic Regression

## Importing the libraries

In [38]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [39]:
dataset = pd.read_csv('./train.csv')
dataset = dataset.dropna(how='any', subset=['Embarked'])
X_train = dataset.iloc[:, [2, 4, 6, 7, 9, 11]].values
y_train = dataset.iloc[:, 1].values

dataset = pd.read_csv('./test.csv')
X_test = dataset.iloc[:, [1, 3, 5, 6, 8, 10]].values
y_pid = dataset.iloc[:, [0]].values

## Printing data

In [40]:
print(X_train)

[[3 'male' 1 0 7.25 'S']
 [1 'female' 1 0 71.2833 'C']
 [3 'female' 0 0 7.925 'S']
 [1 'female' 1 0 53.1 'S']
 [3 'male' 0 0 8.05 'S']
 [3 'male' 0 0 8.4583 'Q']
 [1 'male' 0 0 51.8625 'S']
 [3 'male' 3 1 21.075 'S']
 [3 'female' 0 2 11.1333 'S']
 [2 'female' 1 0 30.0708 'C']
 [3 'female' 1 1 16.7 'S']
 [1 'female' 0 0 26.55 'S']
 [3 'male' 0 0 8.05 'S']
 [3 'male' 1 5 31.275 'S']
 [3 'female' 0 0 7.8542 'S']
 [2 'female' 0 0 16.0 'S']
 [3 'male' 4 1 29.125 'Q']
 [2 'male' 0 0 13.0 'S']
 [3 'female' 1 0 18.0 'S']
 [3 'female' 0 0 7.225 'C']
 [2 'male' 0 0 26.0 'S']
 [2 'male' 0 0 13.0 'S']
 [3 'female' 0 0 8.0292 'Q']
 [1 'male' 0 0 35.5 'S']
 [3 'female' 3 1 21.075 'S']
 [3 'female' 1 5 31.3875 'S']
 [3 'male' 0 0 7.225 'C']
 [1 'male' 3 2 263.0 'S']
 [3 'female' 0 0 7.8792 'Q']
 [3 'male' 0 0 7.8958 'S']
 [1 'male' 0 0 27.7208 'C']
 [1 'female' 1 0 146.5208 'C']
 [3 'female' 0 0 7.75 'Q']
 [2 'male' 0 0 10.5 'S']
 [1 'male' 1 0 82.1708 'C']
 [1 'male' 1 0 52.0 'S']
 [3 'male' 0 0 7.2

In [41]:
print(X_test)

[[3 'male' 0 0 7.8292 'Q']
 [3 'female' 1 0 7.0 'S']
 [2 'male' 0 0 9.6875 'Q']
 [3 'male' 0 0 8.6625 'S']
 [3 'female' 1 1 12.2875 'S']
 [3 'male' 0 0 9.225 'S']
 [3 'female' 0 0 7.6292 'Q']
 [2 'male' 1 1 29.0 'S']
 [3 'female' 0 0 7.2292 'C']
 [3 'male' 2 0 24.15 'S']
 [3 'male' 0 0 7.8958 'S']
 [1 'male' 0 0 26.0 'S']
 [1 'female' 1 0 82.2667 'S']
 [2 'male' 1 0 26.0 'S']
 [1 'female' 1 0 61.175 'S']
 [2 'female' 1 0 27.7208 'C']
 [2 'male' 0 0 12.35 'Q']
 [3 'male' 0 0 7.225 'C']
 [3 'female' 1 0 7.925 'S']
 [3 'female' 0 0 7.225 'C']
 [1 'male' 1 0 59.4 'C']
 [3 'male' 0 1 3.1708 'S']
 [1 'female' 0 0 31.6833 'S']
 [1 'male' 0 1 61.3792 'C']
 [1 'female' 1 3 262.375 'C']
 [3 'male' 1 0 14.5 'S']
 [1 'female' 0 1 61.9792 'C']
 [3 'male' 0 0 7.225 'C']
 [1 'male' 0 0 30.5 'S']
 [3 'male' 2 0 21.6792 'C']
 [2 'male' 1 0 26.0 'S']
 [2 'male' 2 0 31.5 'S']
 [3 'female' 1 2 20.575 'S']
 [3 'female' 1 2 23.45 'S']
 [1 'male' 1 0 57.75 'C']
 [3 'male' 0 0 7.2292 'C']
 [3 'female' 0 0 8.0

In [42]:
print(y_train)

[0 1 1 1 0 0 0 0 1 1 1 1 0 0 0 1 0 1 0 1 0 1 1 1 0 1 0 0 1 0 0 1 1 0 0 0 1
 0 0 1 0 0 0 1 1 0 0 1 0 0 0 0 1 1 0 1 1 0 1 0 0 0 0 0 1 1 0 1 0 0 0 0 0 1
 0 0 0 1 1 0 1 1 0 1 1 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 1 0 0 0 0 1 0 0 1 0 0 0 0 1 1 0 0 0 1 0 0
 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0
 1 1 0 0 1 0 1 1 1 1 0 0 1 0 0 0 0 0 1 0 0 1 1 1 0 1 0 0 0 1 1 0 1 0 1 0 0
 0 1 0 1 0 0 0 1 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 1 1 1
 0 1 0 0 0 0 0 1 1 1 0 1 1 0 1 1 0 0 0 1 0 0 0 1 0 0 1 0 1 1 1 1 0 0 0 0 0
 0 1 1 1 1 0 1 0 1 1 1 0 1 1 1 0 0 0 1 1 0 1 1 0 0 1 1 0 1 0 1 1 1 1 0 0 0
 1 0 0 1 1 0 1 1 0 0 0 1 1 1 1 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 1 1 1 1 1
 0 0 0 0 1 1 0 0 0 1 1 0 1 0 0 0 1 0 1 1 1 0 1 1 0 0 0 0 1 1 0 0 0 0 0 0 1
 0 0 0 0 1 0 1 0 1 1 0 0 0 0 0 0 0 0 1 1 0 1 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1
 1 1 1 1 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 1 0 0
 0 1 1 0 1 0 0 1 0 0 0 0 

## Label encode M/F

In [43]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X_train[:,1] = le.fit_transform(X_train[:,1])
print(X_train)

X_test[:,1] = le.transform(X_test[:,1])
print(X_test)

[[3 1 1 0 7.25 'S']
 [1 0 1 0 71.2833 'C']
 [3 0 0 0 7.925 'S']
 [1 0 1 0 53.1 'S']
 [3 1 0 0 8.05 'S']
 [3 1 0 0 8.4583 'Q']
 [1 1 0 0 51.8625 'S']
 [3 1 3 1 21.075 'S']
 [3 0 0 2 11.1333 'S']
 [2 0 1 0 30.0708 'C']
 [3 0 1 1 16.7 'S']
 [1 0 0 0 26.55 'S']
 [3 1 0 0 8.05 'S']
 [3 1 1 5 31.275 'S']
 [3 0 0 0 7.8542 'S']
 [2 0 0 0 16.0 'S']
 [3 1 4 1 29.125 'Q']
 [2 1 0 0 13.0 'S']
 [3 0 1 0 18.0 'S']
 [3 0 0 0 7.225 'C']
 [2 1 0 0 26.0 'S']
 [2 1 0 0 13.0 'S']
 [3 0 0 0 8.0292 'Q']
 [1 1 0 0 35.5 'S']
 [3 0 3 1 21.075 'S']
 [3 0 1 5 31.3875 'S']
 [3 1 0 0 7.225 'C']
 [1 1 3 2 263.0 'S']
 [3 0 0 0 7.8792 'Q']
 [3 1 0 0 7.8958 'S']
 [1 1 0 0 27.7208 'C']
 [1 0 1 0 146.5208 'C']
 [3 0 0 0 7.75 'Q']
 [2 1 0 0 10.5 'S']
 [1 1 1 0 82.1708 'C']
 [1 1 1 0 52.0 'S']
 [3 1 0 0 7.2292 'C']
 [3 1 0 0 8.05 'S']
 [3 0 2 0 18.0 'S']
 [3 0 1 0 11.2417 'C']
 [3 0 1 0 9.475 'S']
 [2 0 1 0 21.0 'S']
 [3 1 0 0 7.8958 'C']
 [2 0 1 2 41.5792 'C']
 [3 0 0 0 7.8792 'Q']
 [3 1 0 0 8.05 'S']
 [3 1 1 0 15.5 'Q']

## Onehot encode station

In [44]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [5])], remainder='passthrough') # Transforms last column
X_train = np.array(ct.fit_transform(X_train))

X_test = np.array(ct.transform(X_test))

In [45]:
np.set_printoptions(threshold=np.inf)
print(X_train)

[[0.0 0.0 1.0 3 1 1 0 7.25]
 [1.0 0.0 0.0 1 0 1 0 71.2833]
 [0.0 0.0 1.0 3 0 0 0 7.925]
 [0.0 0.0 1.0 1 0 1 0 53.1]
 [0.0 0.0 1.0 3 1 0 0 8.05]
 [0.0 1.0 0.0 3 1 0 0 8.4583]
 [0.0 0.0 1.0 1 1 0 0 51.8625]
 [0.0 0.0 1.0 3 1 3 1 21.075]
 [0.0 0.0 1.0 3 0 0 2 11.1333]
 [1.0 0.0 0.0 2 0 1 0 30.0708]
 [0.0 0.0 1.0 3 0 1 1 16.7]
 [0.0 0.0 1.0 1 0 0 0 26.55]
 [0.0 0.0 1.0 3 1 0 0 8.05]
 [0.0 0.0 1.0 3 1 1 5 31.275]
 [0.0 0.0 1.0 3 0 0 0 7.8542]
 [0.0 0.0 1.0 2 0 0 0 16.0]
 [0.0 1.0 0.0 3 1 4 1 29.125]
 [0.0 0.0 1.0 2 1 0 0 13.0]
 [0.0 0.0 1.0 3 0 1 0 18.0]
 [1.0 0.0 0.0 3 0 0 0 7.225]
 [0.0 0.0 1.0 2 1 0 0 26.0]
 [0.0 0.0 1.0 2 1 0 0 13.0]
 [0.0 1.0 0.0 3 0 0 0 8.0292]
 [0.0 0.0 1.0 1 1 0 0 35.5]
 [0.0 0.0 1.0 3 0 3 1 21.075]
 [0.0 0.0 1.0 3 0 1 5 31.3875]
 [1.0 0.0 0.0 3 1 0 0 7.225]
 [0.0 0.0 1.0 1 1 3 2 263.0]
 [0.0 1.0 0.0 3 0 0 0 7.8792]
 [0.0 0.0 1.0 3 1 0 0 7.8958]
 [1.0 0.0 0.0 1 1 0 0 27.7208]
 [1.0 0.0 0.0 1 0 1 0 146.5208]
 [0.0 1.0 0.0 3 0 0 0 7.75]
 [0.0 0.0 1.0 2 1 0 0 10.5]
 [1

In [46]:
print(X_test)

[[0.0 1.0 0.0 3 1 0 0 7.8292]
 [0.0 0.0 1.0 3 0 1 0 7.0]
 [0.0 1.0 0.0 2 1 0 0 9.6875]
 [0.0 0.0 1.0 3 1 0 0 8.6625]
 [0.0 0.0 1.0 3 0 1 1 12.2875]
 [0.0 0.0 1.0 3 1 0 0 9.225]
 [0.0 1.0 0.0 3 0 0 0 7.6292]
 [0.0 0.0 1.0 2 1 1 1 29.0]
 [1.0 0.0 0.0 3 0 0 0 7.2292]
 [0.0 0.0 1.0 3 1 2 0 24.15]
 [0.0 0.0 1.0 3 1 0 0 7.8958]
 [0.0 0.0 1.0 1 1 0 0 26.0]
 [0.0 0.0 1.0 1 0 1 0 82.2667]
 [0.0 0.0 1.0 2 1 1 0 26.0]
 [0.0 0.0 1.0 1 0 1 0 61.175]
 [1.0 0.0 0.0 2 0 1 0 27.7208]
 [0.0 1.0 0.0 2 1 0 0 12.35]
 [1.0 0.0 0.0 3 1 0 0 7.225]
 [0.0 0.0 1.0 3 0 1 0 7.925]
 [1.0 0.0 0.0 3 0 0 0 7.225]
 [1.0 0.0 0.0 1 1 1 0 59.4]
 [0.0 0.0 1.0 3 1 0 1 3.1708]
 [0.0 0.0 1.0 1 0 0 0 31.6833]
 [1.0 0.0 0.0 1 1 0 1 61.3792]
 [1.0 0.0 0.0 1 0 1 3 262.375]
 [0.0 0.0 1.0 3 1 1 0 14.5]
 [1.0 0.0 0.0 1 0 0 1 61.9792]
 [1.0 0.0 0.0 3 1 0 0 7.225]
 [0.0 0.0 1.0 1 1 0 0 30.5]
 [1.0 0.0 0.0 3 1 2 0 21.6792]
 [0.0 0.0 1.0 2 1 1 0 26.0]
 [0.0 0.0 1.0 2 1 2 0 31.5]
 [0.0 0.0 1.0 3 0 1 2 20.575]
 [0.0 0.0 1.0 3 0 1 2 23.45]

## Take care of missing fare in test data

In [47]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X_train[:, 7:8])
X_test[:, 7:8] = imputer.transform(X_test[:, 7:8])

#X_test[-1].fillna(X_train[-1].mean(), inplace=True)

print(X_test)

[[0.0 1.0 0.0 3 1 0 0 7.8292]
 [0.0 0.0 1.0 3 0 1 0 7.0]
 [0.0 1.0 0.0 2 1 0 0 9.6875]
 [0.0 0.0 1.0 3 1 0 0 8.6625]
 [0.0 0.0 1.0 3 0 1 1 12.2875]
 [0.0 0.0 1.0 3 1 0 0 9.225]
 [0.0 1.0 0.0 3 0 0 0 7.6292]
 [0.0 0.0 1.0 2 1 1 1 29.0]
 [1.0 0.0 0.0 3 0 0 0 7.2292]
 [0.0 0.0 1.0 3 1 2 0 24.15]
 [0.0 0.0 1.0 3 1 0 0 7.8958]
 [0.0 0.0 1.0 1 1 0 0 26.0]
 [0.0 0.0 1.0 1 0 1 0 82.2667]
 [0.0 0.0 1.0 2 1 1 0 26.0]
 [0.0 0.0 1.0 1 0 1 0 61.175]
 [1.0 0.0 0.0 2 0 1 0 27.7208]
 [0.0 1.0 0.0 2 1 0 0 12.35]
 [1.0 0.0 0.0 3 1 0 0 7.225]
 [0.0 0.0 1.0 3 0 1 0 7.925]
 [1.0 0.0 0.0 3 0 0 0 7.225]
 [1.0 0.0 0.0 1 1 1 0 59.4]
 [0.0 0.0 1.0 3 1 0 1 3.1708]
 [0.0 0.0 1.0 1 0 0 0 31.6833]
 [1.0 0.0 0.0 1 1 0 1 61.3792]
 [1.0 0.0 0.0 1 0 1 3 262.375]
 [0.0 0.0 1.0 3 1 1 0 14.5]
 [1.0 0.0 0.0 1 0 0 1 61.9792]
 [1.0 0.0 0.0 3 1 0 0 7.225]
 [0.0 0.0 1.0 1 1 0 0 30.5]
 [1.0 0.0 0.0 3 1 2 0 21.6792]
 [0.0 0.0 1.0 2 1 1 0 26.0]
 [0.0 0.0 1.0 2 1 2 0 31.5]
 [0.0 0.0 1.0 3 0 1 2 20.575]
 [0.0 0.0 1.0 3 0 1 2 23.45]

## Feature Scaling

In [48]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train) # Scaling all IVs
X_test = sc.transform(X_test)

In [49]:
print(X_train)

[[-4.82710792e-01 -3.07940881e-01  6.16793955e-01  8.25208629e-01
   7.35342031e-01  4.31350239e-01 -4.74325852e-01 -5.00239751e-01]
 [ 2.07163382e+00 -3.07940881e-01 -1.62128697e+00 -1.57221121e+00
  -1.35991138e+00  4.31350239e-01 -4.74325852e-01  7.88946608e-01]
 [-4.82710792e-01 -3.07940881e-01  6.16793955e-01  8.25208629e-01
  -1.35991138e+00 -4.75199081e-01 -4.74325852e-01 -4.86649935e-01]
 [-4.82710792e-01 -3.07940881e-01  6.16793955e-01 -1.57221121e+00
  -1.35991138e+00  4.31350239e-01 -4.74325852e-01  4.22861113e-01]
 [-4.82710792e-01 -3.07940881e-01  6.16793955e-01  8.25208629e-01
   7.35342031e-01 -4.75199081e-01 -4.74325852e-01 -4.84133302e-01]
 [-4.82710792e-01  3.24737656e+00 -1.62128697e+00  8.25208629e-01
   7.35342031e-01 -4.75199081e-01 -4.74325852e-01 -4.75912973e-01]
 [-4.82710792e-01 -3.07940881e-01  6.16793955e-01 -1.57221121e+00
   7.35342031e-01 -4.75199081e-01 -4.74325852e-01  3.97946450e-01]
 [-4.82710792e-01 -3.07940881e-01  6.16793955e-01  8.25208629e-01
   

In [50]:
print(X_test)

[[-4.82710792e-01  3.24737656e+00 -1.62128697e+00  8.25208629e-01
   7.35342031e-01 -4.75199081e-01 -4.74325852e-01 -4.88578682e-01]
 [-4.82710792e-01 -3.07940881e-01  6.16793955e-01  8.25208629e-01
  -1.35991138e+00  4.31350239e-01 -4.74325852e-01 -5.05273016e-01]
 [-4.82710792e-01  3.24737656e+00 -1.62128697e+00 -3.73501291e-01
   7.35342031e-01 -4.75199081e-01 -4.74325852e-01 -4.51165414e-01]
 [-4.82710792e-01 -3.07940881e-01  6.16793955e-01  8.25208629e-01
   7.35342031e-01 -4.75199081e-01 -4.74325852e-01 -4.71801802e-01]
 [-4.82710792e-01 -3.07940881e-01  6.16793955e-01  8.25208629e-01
  -1.35991138e+00  4.31350239e-01  7.65896744e-01 -3.98819454e-01]
 [-4.82710792e-01 -3.07940881e-01  6.16793955e-01  8.25208629e-01
   7.35342031e-01 -4.75199081e-01 -4.74325852e-01 -4.60476955e-01]
 [-4.82710792e-01  3.24737656e+00 -1.62128697e+00  8.25208629e-01
  -1.35991138e+00 -4.75199081e-01 -4.74325852e-01 -4.92605294e-01]
 [-4.82710792e-01 -3.07940881e-01  6.16793955e-01 -3.73501291e-01
   

## Training the Logistic Regression model on the Training set

In [51]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

## Predicting the Test set results

In [52]:
y_pred = classifier.predict(X_test)
output=np.concatenate((y_pid.reshape(len(y_pid),1), y_pred.reshape(len(y_pred),1)),1)
print(output)
np.savetxt("result_linear_regression.csv", output, delimiter=',', header='PassengerId,Survived', fmt='%d', comments='')

[[ 892    0]
 [ 893    1]
 [ 894    0]
 [ 895    0]
 [ 896    1]
 [ 897    0]
 [ 898    1]
 [ 899    0]
 [ 900    1]
 [ 901    0]
 [ 902    0]
 [ 903    0]
 [ 904    1]
 [ 905    0]
 [ 906    1]
 [ 907    1]
 [ 908    0]
 [ 909    0]
 [ 910    1]
 [ 911    1]
 [ 912    0]
 [ 913    0]
 [ 914    1]
 [ 915    1]
 [ 916    1]
 [ 917    0]
 [ 918    1]
 [ 919    0]
 [ 920    0]
 [ 921    0]
 [ 922    0]
 [ 923    0]
 [ 924    1]
 [ 925    1]
 [ 926    0]
 [ 927    0]
 [ 928    1]
 [ 929    1]
 [ 930    0]
 [ 931    0]
 [ 932    0]
 [ 933    0]
 [ 934    0]
 [ 935    1]
 [ 936    1]
 [ 937    0]
 [ 938    0]
 [ 939    0]
 [ 940    1]
 [ 941    1]
 [ 942    0]
 [ 943    0]
 [ 944    1]
 [ 945    1]
 [ 946    0]
 [ 947    0]
 [ 948    0]
 [ 949    0]
 [ 950    0]
 [ 951    1]
 [ 952    0]
 [ 953    0]
 [ 954    0]
 [ 955    1]
 [ 956    0]
 [ 957    1]
 [ 958    1]
 [ 959    0]
 [ 960    0]
 [ 961    1]
 [ 962    1]
 [ 963    0]
 [ 964    1]
 [ 965    0]
 [ 966    1]
 [ 967    1]
 [ 968    0]

##  Training the Kernel SVM model on the Training set

In [53]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

SVC(random_state=0)

## Predicting the Test set results

In [54]:
y_pred = classifier.predict(X_test)
output=np.concatenate((y_pid.reshape(len(y_pid),1), y_pred.reshape(len(y_pred),1)),1)
print(output)
np.savetxt("result_kernel_svm.csv", output, delimiter=',', header='PassengerId,Survived', fmt='%d', comments='')

[[ 892    0]
 [ 893    0]
 [ 894    0]
 [ 895    0]
 [ 896    0]
 [ 897    0]
 [ 898    1]
 [ 899    0]
 [ 900    1]
 [ 901    0]
 [ 902    0]
 [ 903    0]
 [ 904    1]
 [ 905    0]
 [ 906    1]
 [ 907    1]
 [ 908    0]
 [ 909    0]
 [ 910    0]
 [ 911    1]
 [ 912    0]
 [ 913    0]
 [ 914    1]
 [ 915    0]
 [ 916    1]
 [ 917    0]
 [ 918    1]
 [ 919    0]
 [ 920    0]
 [ 921    0]
 [ 922    0]
 [ 923    0]
 [ 924    0]
 [ 925    0]
 [ 926    0]
 [ 927    0]
 [ 928    0]
 [ 929    0]
 [ 930    0]
 [ 931    0]
 [ 932    0]
 [ 933    0]
 [ 934    0]
 [ 935    1]
 [ 936    1]
 [ 937    0]
 [ 938    0]
 [ 939    0]
 [ 940    1]
 [ 941    1]
 [ 942    0]
 [ 943    0]
 [ 944    1]
 [ 945    1]
 [ 946    0]
 [ 947    0]
 [ 948    0]
 [ 949    0]
 [ 950    0]
 [ 951    1]
 [ 952    0]
 [ 953    0]
 [ 954    0]
 [ 955    1]
 [ 956    0]
 [ 957    1]
 [ 958    1]
 [ 959    0]
 [ 960    0]
 [ 961    0]
 [ 962    1]
 [ 963    0]
 [ 964    0]
 [ 965    0]
 [ 966    1]
 [ 967    0]
 [ 968    0]

##  Training the Random Forest model on the Training set

In [55]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

## Predicting the Test set results

In [56]:
y_pred = classifier.predict(X_test)
output=np.concatenate((y_pid.reshape(len(y_pid),1), y_pred.reshape(len(y_pred),1)),1)
print(output)
np.savetxt("result_random_forest.csv", output, delimiter=',', header='PassengerId,Survived', fmt='%d', comments='')

[[ 892    0]
 [ 893    1]
 [ 894    0]
 [ 895    0]
 [ 896    1]
 [ 897    0]
 [ 898    0]
 [ 899    0]
 [ 900    1]
 [ 901    0]
 [ 902    0]
 [ 903    0]
 [ 904    1]
 [ 905    0]
 [ 906    1]
 [ 907    1]
 [ 908    0]
 [ 909    0]
 [ 910    0]
 [ 911    1]
 [ 912    1]
 [ 913    0]
 [ 914    1]
 [ 915    0]
 [ 916    1]
 [ 917    0]
 [ 918    1]
 [ 919    0]
 [ 920    1]
 [ 921    0]
 [ 922    0]
 [ 923    0]
 [ 924    0]
 [ 925    0]
 [ 926    1]
 [ 927    0]
 [ 928    0]
 [ 929    0]
 [ 930    0]
 [ 931    1]
 [ 932    1]
 [ 933    0]
 [ 934    0]
 [ 935    1]
 [ 936    1]
 [ 937    0]
 [ 938    0]
 [ 939    0]
 [ 940    1]
 [ 941    1]
 [ 942    0]
 [ 943    0]
 [ 944    1]
 [ 945    1]
 [ 946    0]
 [ 947    0]
 [ 948    0]
 [ 949    0]
 [ 950    0]
 [ 951    1]
 [ 952    0]
 [ 953    0]
 [ 954    0]
 [ 955    1]
 [ 956    0]
 [ 957    1]
 [ 958    1]
 [ 959    0]
 [ 960    0]
 [ 961    0]
 [ 962    1]
 [ 963    0]
 [ 964    1]
 [ 965    0]
 [ 966    1]
 [ 967    0]
 [ 968    0]

##  Training the xGBoost model on the Training set

In [57]:
from xgboost import XGBClassifier
classifier = XGBClassifier()
classifier.fit(X_train, y_train)

XGBClassifier()

## Predicting the Test set results

In [58]:
y_pred = classifier.predict(X_test)
output=np.concatenate((y_pid.reshape(len(y_pid),1), y_pred.reshape(len(y_pred),1)),1)
print(output)
np.savetxt("result_xgboost.csv", output, delimiter=',', header='PassengerId,Survived', fmt='%d', comments='')

[[ 892    0]
 [ 893    1]
 [ 894    0]
 [ 895    0]
 [ 896    1]
 [ 897    0]
 [ 898    1]
 [ 899    0]
 [ 900    1]
 [ 901    0]
 [ 902    0]
 [ 903    0]
 [ 904    1]
 [ 905    0]
 [ 906    1]
 [ 907    1]
 [ 908    0]
 [ 909    0]
 [ 910    1]
 [ 911    1]
 [ 912    1]
 [ 913    0]
 [ 914    1]
 [ 915    0]
 [ 916    1]
 [ 917    0]
 [ 918    1]
 [ 919    0]
 [ 920    0]
 [ 921    0]
 [ 922    0]
 [ 923    0]
 [ 924    1]
 [ 925    0]
 [ 926    1]
 [ 927    0]
 [ 928    0]
 [ 929    0]
 [ 930    0]
 [ 931    1]
 [ 932    1]
 [ 933    0]
 [ 934    0]
 [ 935    1]
 [ 936    1]
 [ 937    0]
 [ 938    0]
 [ 939    0]
 [ 940    1]
 [ 941    1]
 [ 942    0]
 [ 943    0]
 [ 944    1]
 [ 945    1]
 [ 946    0]
 [ 947    0]
 [ 948    0]
 [ 949    0]
 [ 950    0]
 [ 951    1]
 [ 952    0]
 [ 953    0]
 [ 954    0]
 [ 955    1]
 [ 956    1]
 [ 957    1]
 [ 958    1]
 [ 959    0]
 [ 960    0]
 [ 961    1]
 [ 962    1]
 [ 963    0]
 [ 964    1]
 [ 965    0]
 [ 966    1]
 [ 967    0]
 [ 968    0]